In [1]:
import pandas as pd

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jp797498e/twitter-entity-sentiment-analysis")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\mohma\.cache\kagglehub\datasets\jp797498e\twitter-entity-sentiment-analysis\versions\2

In [3]:
col_name=["ID","Entity","Labels","Text"]
data =pd.read_csv(r"C:\Users\mohma\.cache\kagglehub\datasets\jp797498e\twitter-entity-sentiment-analysis\versions\2\twitter_training.csv",names=col_name)
data_vil=pd.read_csv(r"C:\Users\mohma\.cache\kagglehub\datasets\jp797498e\twitter-entity-sentiment-analysis\versions\2\twitter_validation.csv")

In [4]:
data

,ID,Entity,Labels,Text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [5]:
data

,ID,Entity,Labels,Text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [6]:
data["Labels"].value_counts()

Labels
Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [7]:
data = data[data['Labels']!= 'Irrelevant']

In [8]:
data['Labels'].value_counts()

Labels
Negative    22542
Positive    20832
Neutral     18318
Name: count, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
data['Labels'] = encoder.fit_transform(data['Labels'])

C:\Users\mohma\AppData\Local\Temp\ipykernel_18528\1969877191.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Labels'] = encoder.fit_transform(data['Labels'])

In [10]:
data

,ID,Entity,Labels,Text
0,2401,Borderlands,2,im getting on borderlands and i will murder yo...
1,2401,Borderlands,2,I am coming to the borders and I will kill you...
2,2401,Borderlands,2,im getting on borderlands and i will kill you ...
3,2401,Borderlands,2,im coming on borderlands and i will murder you...
4,2401,Borderlands,2,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,2,Just realized that the Windows partition of my...
74678,9200,Nvidia,2,Just realized that my Mac window partition is ...
74679,9200,Nvidia,2,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,2,Just realized between the windows partition of...
74681,9200,Nvidia,2,Just like the windows partition of my Mac is l...

In [11]:
data['Labels'].value_counts()  #negative = 0, positive = 2 , Neutral = 1

Labels
0    22542
2    20832
1    18318
Name: count, dtype: int64

In [12]:
data.head()

,ID,Entity,Labels,Text
0,2401,Borderlands,2,im getting on borderlands and i will murder yo...
1,2401,Borderlands,2,I am coming to the borders and I will kill you...
2,2401,Borderlands,2,im getting on borderlands and i will kill you ...
3,2401,Borderlands,2,im coming on borderlands and i will murder you...
4,2401,Borderlands,2,im getting on borderlands 2 and i will murder ...

In [13]:
data = data[["Text","Labels"]]

In [14]:
data.isna().sum()

Text      571
Labels      0
dtype: int64

In [15]:
data["Text"].size

61692

In [16]:
import re

def clean_text(text):
    text = str(text).lower()  # Hello World! → hello world!
    text = re.sub(r"http\S+", "", text) # http://example.com → ""
    text = re.sub(r"@\w+", "", text) # @user123 → ""
    text = re.sub(r"#", "", text) # "#iphone" → "iphone"
    text = re.sub(r"[^a-zA-Z ]", " ", text) # hello!!! → hello
    text = re.sub(r"\s+", " ", text).strip() #"hello     world  " → "hello world"
    return text



data["clean_text"] = data["Text"].apply(clean_text)

C:\Users\mohma\AppData\Local\Temp\ipykernel_18528\3375403604.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["clean_text"] = data["Text"].apply(clean_text)

In [17]:
data["Labels"]

0        2
1        2
2        2
3        2
4        2
        ..
74677    2
74678    2
74679    2
74680    2
74681    2
Name: Labels, Length: 61692, dtype: int64

In [18]:
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split

# 1) Split
X_train, X_test, y_train, y_test = train_test_split(
    data["clean_text"], data["Labels"], test_size=0.2, random_state=42
)

# 2) Tokenizer fit ONLY on train
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

# 3) Transform train & test
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

In [19]:
data["clean_text"]

0        im getting on borderlands and i will murder yo...
1        i am coming to the borders and i will kill you...
2        im getting on borderlands and i will kill you all
3        im coming on borderlands and i will murder you...
4        im getting on borderlands and i will murder yo...
                               ...
74677    just realized that the windows partition of my...
74678    just realized that my mac window partition is ...
74679    just realized the windows partition of my mac ...
74680    just realized between the windows partition of...
74681    just like the windows partition of my mac is l...
Name: clean_text, Length: 61692, dtype: object

In [20]:
data

,Text,Labels,clean_text
0,im getting on borderlands and i will murder yo...,2,im getting on borderlands and i will murder yo...
1,I am coming to the borders and I will kill you...,2,i am coming to the borders and i will kill you...
2,im getting on borderlands and i will kill you ...,2,im getting on borderlands and i will kill you all
3,im coming on borderlands and i will murder you...,2,im coming on borderlands and i will murder you...
4,im getting on borderlands 2 and i will murder ...,2,im getting on borderlands and i will murder yo...
...,...,...,...
74677,Just realized that the Windows partition of my...,2,just realized that the windows partition of my...
74678,Just realized that my Mac window partition is ...,2,just realized that my mac window partition is ...
74679,Just realized the windows partition of my Mac ...,2,just realized the windows partition of my mac ...
74680,Just realized between the windows partition of...,2,just realized between the windows partition of...
74681,Just like the windows partition of my Mac is l...,2,just like the windows partition of my mac is l...

In [21]:
def extract_hashtags(text):
    text = str(text)
    return re.findall(r"#(\w+)", text)   

def extract_mentions(text):
    text = str(text)
    return re.findall(r"@(\w+)", text) 

data["hashtags"] = data["Text"].apply(extract_hashtags)
data["mentions"] = data["Text"].apply(extract_mentions)

In [22]:
data.to_csv("data_new.csv",index=False)

In [23]:
from sklearn.model_selection import train_test_split

# 1) Split
X_train, X_test, y_train, y_test = train_test_split(
    data["clean_text"], data["Labels"], test_size=0.2, random_state=42,stratify=data["Labels"]
)

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer


tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

In [25]:
X_test_seq

[[1028,
  67,
  193,
  58,
  3619,
  4363,
  104,
  103,
  223,
  2373,
  129,
  7405,
  4,
  17504,
  172,
  156,
  21,
  507,
  9,
  2979,
  4,
  1629,
  9,
  346,
  16,
  15,
  507,
  2077,
  5795,
  2,
  31,
  835,
  163,
  230,
  77,
  34,
  11,
  17,
  198],
 [601,
  1786,
  2,
  118,
  16,
  310,
  2327,
  30,
  27,
  1817,
  10,
  9048,
  26,
  2,
  107,
  103,
  11,
  10,
  49,
  494,
  4,
  418,
  7,
  53,
  3,
  23,
  15645,
  317,
  45,
  116,
  1142,
  1,
  3226,
  8,
  1032,
  3842,
  4,
  274,
  27,
  1543,
  33,
  28,
  1084],
 [1922,
  32,
  5,
  90,
  432,
  53,
  1828,
  378,
  524,
  448,
  907,
  121,
  245,
  17020,
  2734,
  1292,
  53,
  4957,
  393,
  33],
 [9125, 2879, 1036, 6, 3338, 58, 5, 90, 1927, 1261, 1638, 1286, 1261],
 [2, 1495, 18165, 1132, 9, 9151],
 [332, 56],
 [1252,
  47,
  12,
  179,
  258,
  61,
  49,
  1,
  337,
  1321,
  50,
  15,
  1,
  447,
  6,
  254,
  5,
  83,
  1234,
  13,
  2792,
  59,
  61,
  129,
  511,
  6,
  14,
  77,
  5600,
  741,
  4,
  18010],
 [256,
  226,
  2,
  100,
  108,
  3,
  306,
  11,
  3,
  3419,
  4,
  86,
  50,
  18019,
  6,
  5700,
  3,
  949],
 [2,
  290,
  34,
  2,
  84,
  2810,
  1199,
  177,
  23035,
  9,
  170,
  335,
  1123,
  301,
  2101,
  1018,
  42,
  1,
  5175,
  330],
 [284, 156, 229, 2545, 176, 156, 95, 36, 39, 18, 16114],
 [23, 65, 1416, 64],
 [568, 59, 154, 9, 6, 203, 1381, 926, 231, 301, 678, 741, 4, 11253, 2942],
 [2347,
  4823,
  2181,
  15354,
  1050,
  1353,
  2692,
  76,
  5,
  4457,
  3,
  2059,
  6500,
  4,
  5290,
  13043,
  18,
  13044,
  819,
  407,
  2181,
  8,
  162],
 [2,
  24,
  3272,
  14,
  344,
  839,
  233,
  33,
  11,
  19,
  20,
  5,
  2132,
  6,
  1428,
  365,
  1044,
  34,
  267,
  3,
  42,
  55,
  6946,
  4,
  152,
  2,
  168,
  344,
  2,
  698,
  14,
  677,
  635,
  26,
  41,
  124,
  2,
  100,
  2031,
  2009,
  11,
  211,
  14,
  316,
  4605,
  437,
  177,
  175],
 [50,
  1,
  305,
  231,
  149,
  674,
  59,
  149,
  483,
  547,
  149,
  28,
  204,
  5,
  2826,
  10,
  8874,
  11,
  19],
 [423, 29, 3593, 16],
 [40, 3048, 5675, 8, 5, 1432, 220, 1432],
 [1647,
  177,
  224,
  3,
  225,
  2799,
  3,
  22,
  1246,
  851,
  7,
  269,
  17,
  87,
  24,
  3,
  22,
  13,
  1,
  53,
  19,
  2,
  164,
  7,
  126,
  22,
  5,
  90,
  489,
  10,
  71,
  104,
  822,
  17,
  9,
  247,
  16269,
  5,
  2285,
  6,
  1923,
  1828,
  2377,
  7,
  163],
 [230,
  6,
  12,
  30,
  53,
  216,
  1,
  172,
  263,
  212,
  15497,
  26,
  10,
  322,
  104,
  456,
  22,
  220,
  957,
  4850,
  695,
  34,
  23,
  19304,
  820,
  957,
  4850,
  8,
  9,
  1,
  315,
  1,
  153,
  8,
  270,
  26,
  301,
  5426,
  339,
  25,
  607,
  35,
  20,
  366,
  1902],
 [3566,
  2001,
  11,
  1116,
  155,
  28,
  143,
  335,
  2,
  31,
  3822,
  3,
  1432,
  1,
  265,
  60,
  113,
  1,
  265,
  155,
  28,
  737],
 [164,
  294,
  261,
  79,
  361,
  20,
  11,
  114,
  2000,
  377,
  128,
  16,
  460,
  72,
  706,
  49,
  1080,
  50,
  29,
  119,
  14,
  1560,
  720,
  34,
  2,
  31,
  19468,
  706,
  13,
  5,
  13093,
  6215,
  177,
  760],
 [75, 17, 22, 8869],
 [2, 243, 8482],
 [9162,
  14,
  540,
  8,
  9163,
  4,
  2,
  31,
  53,
  124,
  4,
  2,
  24,
  5,
  1515,
  973,
  1583,
  157,
  11578,
  134,
  6,
  1,
  71,
  66,
  337,
  3727,
  2690,
  233,
  4,
  85,
  3588,
  30,
  131,
  421,
  11579,
  164,
  9164,
  68,
  71,
  164,
  10,
  28,
  123,
  1,
  1648,
  534],
 [829, 113, 40, 351, 19, 53, 610, 1344, 27, 2932, 14, 1610],
 [2,
  100,
  2341,
  3,
  1136,
  16,
  2,
  32,
  388,
  6,
  1,
  2062,
  196,
  6,
  173,
  308,
  321,
  247,
  396,
  3797,
  10,
  193,
  104,
  839,
  20,
  23,
  13,
  7,
  4,
  6414,
  1,
  604,
  6206,
  249,
  18,
  171,
  137,
  9211,
  246],
 [16652, 48, 61, 374],
 [1858, 107, 2222, 45, 117],
 [21, 230, 226, 71, 9, 1, 2382, 15, 633],
 [791, 3, 522, 401, 14, 146, 115],
 [11, 70, 381, 733, 505, 6, 203, 1496, 1576, 350, 486, 1695],
 [30,
  38,
  108,
  3,
  819,
  5602,
  124,
  16,
  4,
  27,
  1312,
  16,
  43,
  30,
  315,
  12,
  139,
  620,
  424,
  38,
  30,
  647],
 [93, 330, 625, 5, 418, 5, 336, 772, 59, 1, 53, 501, 314, 32, 1768],
 [1855,
  425,
  389,
  1022,
  2,
  24,
  481,
  16,
  547,
  4060,
  58,
  72,
  667,
  471,
  3,
  7011,
  20029,
  1436,
  2,
  24,
  3,
  2408,
  16,
  68,
  6,
  1,
  3146,
  2,
  1122,
  20,
  4,
  874,
  30,
  25,
  351,
  36,
  39,
  18,
  14307,
  14308],
 [96, 82, 141, 1106, 3, 10568, 17, 198, 83, 246, 20086],
 [3290,
  52,
  194,
  115,
  804,
  66,
  88,
  522,
  401,
  1518,
  738,
  4589,
  662,
  1276,
  7,
  3,
  14,
  349,
  66,
  2790,
  44,
  449,
  44,
  149,
  97,
  368,
  35,
  52,
  149,
  89,
  20,
  23],
 [8,
  108,
  35,
  58,
  201,
  23,
  1561,
  65,
  70,
  100,
  20,
  1,
  259,
  8349,
  4,
  28,
  93,
  2183,
  113,
  313,
  1354,
  469,
  4,
  1,
  897,
  8,
  596,
  15180],
 [1448, 257, 60, 13, 1220, 210, 2458, 14, 344, 881, 37, 16, 883, 70, 19, 1476],
 [1010, 2150, 1943, 4, 2, 34, 7],
 [1, 134, 4824, 53, 94, 146, 115, 8, 5, 19, 12761, 601, 18, 4, 94, 15],
 [571,
  10,
  61,
  2312,
  227,
  19,
  4,
  61,
  1256,
  487,
  16372,
  4,
  73,
  554,
  2056,
  806,
  69,
  1,
  15095],
 [346,
  2,
  873,
  17,
  5,
  337,
  26,
  2,
  81,
  5,
  16783,
  2001,
  155,
  28,
  155,
  28,
  204,
  3,
  609,
  3,
  104,
  274,
  626,
  1469,
  911,
  145,
  156,
  12,
  1979,
  105,
  172,
  156,
  12,
  651,
  1486,
  8324,
  4664],
 [741, 402],
 [94, 146, 20, 1996, 207, 793, 850, 4, 23302, 752, 195, 94, 146, 115],
 [394, 47, 11, 97],
 [533,
  7,
  183,
  5118,
  4,
  5118,
  10,
  680,
  129,
  1,
  94,
  146,
  115,
  179,
  2,
  75,
  17,
  164,
  115,
  8,
  1,
  162,
  1465,
  10,
  23,
  26,
  41,
  2,
  31,
  61,
  6027],
 [946, 268, 686, 149, 15],
 [10660,
  144,
  12,
  10,
  3359,
  9,
  971,
  171,
  1,
  153,
  3,
  86,
  52,
  12,
  24,
  178,
  55,
  74,
  3632,
  455,
  764,
  145,
  130,
  10,
  194,
  372,
  3,
  238,
  45,
  41,
  10,
  218,
  1082,
  1082,
  2314,
  838,
  17,
  198,
  20925,
  20926],
 [307,
  4669,
  4330,
  60,
  1511,
  1200,
  96,
  1307,
  4764,
  154,
  35,
  3940,
  347,
  14020,
  946,
  268,
  4484,
  953,
  309],
 [11,
  8,
  93,
  507,
  2041,
  523,
  122,
  428,
  5,
  611,
  16,
  1512,
  3321,
  642,
  4,
  183,
  34,
  3710,
  2,
  688,
  290,
  135,
  10,
  102,
  152,
  2,
  43,
  45,
  2548,
  1839],
 [128,
  5,
  20616,
  2602,
  20,
  74,
  4,
  2,
  190,
  27,
  401,
  376,
  174,
  2,
  2034,
  5,
  1955,
  37,
  14,
  2399,
  3155,
  5811,
  23,
  10,
  1645,
  291,
  1446],
 [232, 171, 23, 14458, 14, 3917],
 [346, 12, 697],
 [154, 6, 203, 15, 1257, 8, 550, 129, 3903, 4275, 15, 4159, 421, 131, 421],
 [38, 30, 593, 3, 22, 334, 20, 22315, 13, 275, 4, 790, 5020, 33, 892],
 [21,
  214,
  1186,
  1727,
  8,
  286,
  152,
  92,
  7,
  58,
  5,
  295,
  6,
  408,
  4492,
  219,
  124,
  104,
  30,
  73,
  25,
  34,
  282,
  23,
  262,
  4,
  420,
  17,
  169,
  1,
  53,
  19,
  9,
  123,
  180,
  26,
  163,
  135,
  1,
  19,
  8,
  27,
  25,
  1629,
  550,
  129,
  1,
  714,
  4010,
  4792],
 [2, 281, 254, 682, 459, 20, 151, 236, 13, 1, 2327, 4, 7, 15, 27, 1, 379],
 [205, 2262, 3, 40, 541, 13, 88, 7, 15, 28, 25, 91, 769, 109, 11],
 [767, 3, 212, 10, 6069, 5, 1282, 14463, 314, 9, 110, 2073, 4200],
 [127,
  2764,
  281,
  283,
  17609,
  1651,
  33,
  40,
  6051,
  17610,
  101,
  150,
  95,
  95,
  95,
  95,
  36,
  39,
  18,
  17611,
  83],
 [1,
  1428,
  212,
  1044,
  15971,
  518,
  410,
  4423,
  13725,
  7007,
  3559,
  237,
  1330,
  142,
  112,
  15972],
 [2, 25, 1562, 9401, 15, 1341, 1008],
 [5414, 1998, 5414],
 [11880,
  1586,
  1586,
  6145,
  807,
  3429,
  4,
  4083,
  294,
  504,
  38,
  826,
  17,
  812,
  12,
  904,
  147,
  2013],
 [81,
  1251,
  123,
  9,
  5,
  1403,
  1008,
  92,
  2,
  81,
  1681,
  2056,
  2,
  1299,
  2950,
  1431,
  445,
  43,
  139,
  25,
  5,
  646,
  6030,
  288,
  109,
  28,
  4,
  859,
  16,
  407,
  12,
  99,
  244,
  66,
  87,
  636,
  6,
  487,
  30,
  3,
  22,
  1787,
  4,
  85,
  8,
  56,
  224,
  10,
  102,
  29,
  285,
  219],
 [50, 1, 89],
 [7436,
  2098,
  3997,
  849,
  50,
  637,
  69,
  8099,
  1328,
  13,
  11,
  66,
  107,
  328,
  1117,
  76,
  18,
  759,
  20248,
  20249,
  20250,
  159,
  17,
  20251,
  317],
 [54, 16231, 1522, 20, 604],
 [114, 2540, 1003, 7024, 268, 284, 83, 345],
 [212, 316, 2425, 890, 24, 125, 1184, 3, 198],
 [1, 1003],
 [3,
  801,
  61,
  6,
  14,
  605,
  278,
  79,
  196,
  170,
  6,
  669,
  160,
  20,
  976,
  1677,
  16,
  139,
  15,
  1,
  447],
 [136, 264, 35, 11, 161, 761],
 [297,
  117,
  3884,
  18383,
  15631,
  18,
  882,
  117,
  19989,
  1236,
  423,
  17,
  198,
  21031,
  21032],
 [10162,
  4234,
  10,
  19643,
  5,
  336,
  260,
  6,
  132,
  2,
  81,
  614,
  9,
  631,
  10,
  168,
  477,
  21,
  2,
  29,
  17,
  119,
  60,
  62,
  504,
  14,
  2140,
  142,
  112,
  17146],
 [33,
  1,
  227,
  62,
  598,
  1,
  404,
  16,
  85,
  30,
  458,
  68,
  464,
  71,
  669,
  608,
  1,
  879,
  440,
  134,
  6,
  102,
  47,
  27,
  24,
  280,
  3,
  273,
  454,
  4,
  47,
  27,
  24,
  280,
  3,
  273,
  258,
  211,
  134,
  6,
  102,
  47,
  27,
  24,
  280,
  3,
  273,
  258],
 [26, 2, 29, 17, 6107],
 [301,
  176,
  20,
  11,
  2760,
  6,
  14,
  304,
  450,
  11,
  348,
  4,
  14,
  799,
  304,
  450,
  6,
  569,
  104,
  8,
  40,
  304,
  450,
  6,
  569],
 [6448, 4886, 1506, 21040, 30, 334, 13, 55, 1716, 349, 4, 3391, 615, 15, 3161],
 [],
 [303],
 [14, 1687, 8, 16324, 4, 14, 130, 8, 1491],
 [1, 528, 516, 1539, 12469, 17071, 1180, 1065, 12470, 8227],
 [257, 1, 763, 226, 5533, 163],
 [220, 16373, 8, 27, 1588],
 [63, 302],
 [145, 62, 2, 342, 4, 243, 463, 10, 7, 128, 8, 48, 6, 339, 244],
 [65, 190, 346, 45, 5, 550, 19, 129, 319, 83],
 [2,
  118,
  16,
  14067,
  1057,
  32,
  1256,
  9,
  11026,
  21,
  270,
  470,
  445,
  7,
  460,
  34,
  5,
  1544,
  3,
  24,
  105,
  25,
  147,
  1143,
  177,
  1686,
  10,
  5,
  591,
  5322,
  6,
  11026,
  387,
  208,
  87,
  225,
  1,
  1420,
  416,
  10,
  7,
  44,
  55,
  527],
 [199, 597, 1067, 204, 3, 24, 68, 90, 93, 77, 189],
 [1716, 969, 208, 41, 384, 61, 129, 242, 622, 736],
 [7],
 [25,
  50,
  403,
  2,
  350,
  10,
  202,
  942,
  235,
  436,
  2058,
  548,
  4,
  41,
  68,
  419,
  3,
  281,
  105,
  272,
  28,
  3036],
 [35,
  6,
  28,
  1,
  349,
  3441,
  3,
  24,
  15987,
  4643,
  116,
  8,
  1,
  107,
  3,
  27,
  24,
  7,
  4,
  2,
  1701,
  24,
  55,
  580,
  20,
  14,
  349],
 [2,
  75,
  17,
  575,
  67,
  11,
  19,
  58,
  576,
  21,
  270,
  216,
  1,
  32,
  655,
  6,
  5,
  23828,
  1461],
 [30, 94, 265, 182, 66, 24, 2, 72, 1318],
 [3049, 2992],
 [829,
  453,
  703,
  1761,
  2,
  100,
  210,
  81,
  1825,
  167,
  3,
  14,
  121,
  116,
  962,
  2,
  31,
  136,
  21,
  221,
  3,
  171,
  1,
  8085,
  4,
  25,
  940,
  701,
  22437,
  70],
 [4007,
  3963,
  13711,
  5637,
  7372,
  7373,
  6828,
  4347,
  4007,
  74,
  18,
  1425,
  345,
  427,
  13712,
  215,
  74],
 [2,
  84,
  1856,
  983,
  8467,
  1158,
  101,
  150,
  4,
  28,
  10829,
  754,
  398,
  1452,
  16,
  281,
  105,
  28,
  827],
 [7, 15, 21, 326, 59, 11, 854],
 [78, 497, 9, 1, 19, 394, 1151, 23],
 [27, 5, 51, 4305, 10, 677, 20],
 [209,
  238,
  5,
  114,
  1254,
  492,
  53,
  153,
  188,
  22,
  9189,
  9190,
  84,
  1824,
  3506,
  13,
  153,
  7752,
  7491],
 [104, 2210, 197, 23, 11, 70, 294, 1760, 3, 596, 376],
 [585],
 [48, 69, 1, 78, 4556, 219, 69, 4],
 [282,
  1707,
  54,
  6648,
  34,
  23,
  4,
  350,
  34,
  431,
  32,
  108,
  3,
  1589,
  291,
  116,
  354,
  92,
  1088,
  2,
  753,
  291,
  50,
  38,
  394,
  168,
  13,
  20006,
  3921,
  4,
  12,
  364,
  113,
  3,
  7,
  34,
  467,
  64],
 [346,
  257,
  105,
  1,
  3268,
  4724,
  373,
  1798,
  217,
  8,
  279,
  226,
  3,
  86,
  33,
  11,
  156,
  15,
  301,
  2608],
 [264, 35, 1, 761, 2, 25, 81, 1282, 15499, 12096],
 [64,
  64,
  26,
  67,
  12,
  197,
  531,
  3285,
  11,
  6619,
  114,
  22,
  1,
  297,
  4,
  65,
  4,
  152,
  16,
  15,
  56,
  51,
  56,
  53,
  77,
  285,
  6619,
  209,
  50,
  795,
  701,
  1952,
  3979,
  56,
  504,
  154,
  6,
  203,
  693,
  731,
  5701,
  56,
  504,
  40,
  488],
 [2, 416, 3, 47, 11, 111, 1091, 1497, 4599, 30, 14739],
 [38,
  139,
  99,
  477,
  37,
  100,
  79,
  4985,
  1818,
  1178,
  1,
  537,
  170,
  38,
  84,
  483,
  1,
  255,
  6,
  6263,
  24,
  5,
  90,
  2812,
  771,
  4,
  51,
  555,
  9],
 [43,
  24,
  213,
  2858,
  51,
  219,
  10,
  1214,
  56,
  930,
  2566,
  7,
  8,
  9,
  234,
  367,
  91,
  26,
  43,
  84,
  213,
  1191,
  43,
  139,
  25,
  5270,
  3,
  6259,
  385,
  15,
  6222,
  15969,
  874,
  168,
  92,
  12,
  420,
  17,
  5222,
  376,
  1261,
  2090,
  13722,
  353],
 [97,
  683,
  11,
  6610,
  3374,
  15,
  101,
  457,
  97,
  4,
  144,
  12,
  7,
  490,
  27,
  254,
  1,
  15,
  101,
  59,
  27,
  254,
  1,
  11811],
 [2, 63, 170, 6, 160, 142, 112, 14772],
 [13,
  297,
  165,
  16,
  12,
  1589,
  1,
  401,
  26,
  12,
  1174,
  16,
  630,
  58,
  1712,
  1,
  401,
  3727,
  12,
  140,
  3,
  14703],
 [303],
 [117, 661, 8, 1, 326, 626, 117, 6, 28, 62],
 [2, 504, 26, 67, 762, 21, 121, 307, 33, 81, 23, 667],
 [8369,
  8,
  69,
  375,
  1,
  326,
  379,
  2,
  84,
  138,
  103,
  193,
  841,
  3,
  324,
  5,
  392,
  20,
  23,
  4,
  38,
  29,
  306,
  1,
  227,
  4586,
  44,
  116,
  4,
  1485,
  4,
  33,
  17,
  38,
  29,
  193,
  20,
  3085,
  3131,
  4154,
  143,
  14,
  2741,
  58,
  7],
 [563, 2, 206, 878],
 [570,
  2298,
  298,
  2298,
  25,
  41,
  169,
  1,
  121,
  1534,
  10,
  11,
  348,
  292,
  887,
  12,
  190,
  5,
  90,
  168,
  13,
  1,
  347,
  4,
  1,
  8556,
  364,
  143,
  10,
  1,
  199,
  48,
  49,
  168],
 [534,
  600,
  23,
  35,
  80,
  8,
  108,
  3,
  1657,
  5,
  2929,
  35,
  6,
  111,
  259,
  3,
  54,
  2368,
  67,
  12,
  202,
  2715,
  55,
  94,
  146,
  115,
  1715,
  5,
  88],
 [5, 3868, 20921, 3, 119, 5, 15480, 1245, 132, 142, 112, 15481],
 [425,
  67,
  58,
  1,
  501,
  6,
  1,
  94,
  48,
  115,
  72,
  3652,
  15399,
  216,
  1,
  172,
  225,
  131,
  1402,
  1804],
 [2,
  24,
  4762,
  1025,
  10,
  5578,
  763,
  104,
  1239,
  33,
  1,
  3244,
  3468,
  101,
  150,
  1232,
  15,
  9,
  1,
  321,
  2543,
  28,
  3442,
  25,
  3,
  42,
  12040],
 [114,
  18,
  732,
  105,
  9545,
  408,
  7256,
  670,
  4937,
  9546,
  3428,
  20,
  20709,
  4,
  218,
  15562,
  10,
  8357,
  3685,
  9548,
  18,
  2812,
  114],
 [101,
  150,
  3446,
  1725,
  10764,
  16,
  1680,
  5590,
  123,
  4538,
  4,
  24,
  5459,
  2406,
  330,
  453,
  2264,
  34,
  10765],
 [3975, 20, 2039, 96, 9, 4140, 13499, 18, 3537],
 [16,
  15,
  162,
  26,
  11,
  70,
  2944,
  14,
  645,
  2,
  84,
  72,
  79,
  1850,
  216,
  110,
  371,
  4,
  446,
  2973,
  216,
  1,
  121,
  19,
  2,
  31,
  421,
  3,
  86,
  7,
  1003,
  2215,
  33,
  5,
  492,
  569],
 [11,
  491,
  55,
  408,
  3107,
  1465,
  75,
  17,
  42,
  23,
  433,
  104,
  63,
  12505,
  12506,
  3107,
  10,
  7,
  460,
  5,
  336,
  165,
  2,
  31,
  2017,
  2,
  42,
  3229,
  433,
  445],
 [2,
  416,
  5,
  1019,
  12761,
  4,
  15140,
  3,
  22,
  5,
  844,
  9,
  5,
  245,
  512,
  145,
  312,
  4,
  41,
  14,
  1884,
  30,
  4954,
  1557],
 [40,
  872,
  8,
  5,
  93,
  868,
  1611,
  6852,
  16464,
  7,
  15,
  34,
  1696,
  6,
  12,
  93,
  4968,
  187,
  169,
  1134,
  332,
  29,
  17,
  143,
  1087,
  83,
  4391,
  12,
  93,
  2281,
  35,
  6,
  392,
  47,
  228,
  2060,
  10,
  5,
  434,
  4,
  612,
  99,
  18461,
  93,
  952],
 [78,
  388,
  8,
  133,
  6639,
  250,
  15,
  4206,
  367,
  91,
  10,
  3324,
  188,
  22,
  246,
  11427,
  330,
  17],
 [59, 12, 368, 35, 12, 84, 1814, 785, 1, 94, 48, 115, 505, 6, 1, 94, 146, 115],
 [7, 15, 412],
 [530,
  11,
  8,
  162,
  60,
  14,
  16597,
  2,
  1260,
  1241,
  152,
  1111,
  7,
  165,
  2,
  29,
  17,
  324,
  3,
  18918,
  11,
  20,
  14,
  9103,
  9,
  1,
  847],
 [246, 83, 919, 684],
 [74,
  6910,
  60,
  53,
  2544,
  465,
  937,
  3468,
  1529,
  109,
  3202,
  428,
  2501,
  792,
  3044,
  18,
  664,
  3018],
 [5678,
  16,
  218,
  98,
  14484,
  32,
  5,
  507,
  489,
  123,
  18957,
  3,
  24,
  5,
  4431,
  768,
  1244,
  478,
  4,
  2017,
  10097,
  742,
  5678,
  50,
  7,
  223,
  3,
  91,
  45,
  1,
  3681,
  16721,
  33,
  409,
  2592],
 [672,
  6,
  2249,
  6577,
  292,
  38,
  538,
  1,
  71,
  104,
  614,
  12,
  35,
  13,
  40,
  696,
  59,
  12,
  231,
  163,
  93,
  2249,
  3,
  465,
  858,
  9234,
  4,
  3,
  1859,
  3,
  4,
  1205,
  9235,
  10,
  55,
  858,
  1545,
  26,
  12,
  103,
  1,
  62,
  3,
  465,
  49,
  93,
  117,
  4999,
  44,
  52,
  12],
 [14,
  498,
  33,
  7375,
  4933,
  906,
  32,
  1096,
  397,
  15293,
  13,
  98,
  215,
  1949,
  1949,
  18,
  7375,
  4933],
 [468,
  1120,
  6,
  913,
  569,
  574,
  10,
  315,
  5,
  51,
  1438,
  472,
  275,
  5,
  18,
  5,
  284,
  9925],
 [11, 220, 5177, 9, 96, 808, 263, 6, 691, 242, 13, 23],
 [2, 229, 2422, 184, 578],
 [473,
  144,
  12,
  3,
  193,
  104,
  515,
  60,
  69,
  105,
  128,
  504,
  38,
  103,
  3,
  373,
  1,
  451,
  79,
  13,
  5,
  277,
  152,
  7396,
  4,
  17,
  17,
  1192,
  27,
  3995,
  14,
  711,
  87,
  61,
  1,
  451,
  38,
  2508,
  1080,
  908,
  477,
  482,
  87,
  119,
  7,
  28,
  1,
  224,
  305,
  703,
  257,
  33,
  23,
  68,
  61,
  88,
  3243,
  146,
  32,
  301,
  51,
  136],
 [21, 2, 422, 1670, 96, 3476, 4, 781, 71, 10, 56, 429, 441, 23],
 [1,
  698,
  436,
  1259,
  1,
  8607,
  64,
  7457,
  8,
  35,
  41,
  69,
  74,
  734,
  4610,
  1072,
  4,
  161,
  1072,
  50,
  482,
  942,
  59,
  4139,
  210,
  1294,
  847,
  11267,
  65,
  850,
  8,
  15770,
  1,
  8607,
  1106,
  3,
  15771],
 [303],
 [7,
  206,
  15,
  136,
  1402,
  65,
  174,
  184,
  269,
  17,
  87,
  47,
  352,
  177,
  2973,
  4031,
  1207,
  9,
  727,
  19,
  34,
  55,
  3027,
  399,
  250,
  12,
  875,
  242,
  716,
  695,
  10,
  498,
  564,
  4,
  196,
  947,
  4,
  30,
  213,
  13],
 [28,
  162,
  17276,
  8,
  1604,
  1545,
  8,
  73,
  5,
  3923,
  6,
  3955,
  10286,
  8,
  795,
  1,
  19,
  8,
  3608,
  8196,
  1,
  19,
  183,
  161,
  43,
  84,
  210,
  980,
  1,
  2594,
  1227,
  531,
  198,
  20582,
  20583],
 [292, 2, 31, 1151, 221],
 [1669, 9, 3724],
 [41,
  16,
  2,
  84,
  2111,
  910,
  4269,
  6,
  5,
  3765,
  1040,
  2,
  519,
  7,
  61,
  129,
  138,
  87,
  445,
  2,
  107,
  201,
  7,
  3,
  1490,
  6,
  96,
  82,
  141],
 [136,
  924,
  52,
  14,
  189,
  29,
  17,
  197,
  235,
  385,
  88,
  1348,
  6,
  16,
  784,
  488,
  457],
 [7],
 [1046,
  130,
  6,
  12,
  1048,
  5,
  3756,
  37,
  23,
  33,
  11,
  447,
  2,
  258,
  61,
  49,
  12,
  835,
  5,
  3338,
  129,
  1,
  62,
  4,
  233,
  1,
  3756,
  58,
  72,
  455,
  1972],
 [79, 7821, 112, 6720, 42, 20864],
 [48,
  6,
  14,
  380,
  13,
  1,
  88,
  8,
  5,
  10999,
  235,
  76,
  465,
  11,
  478,
  397,
  283,
  9,
  5,
  15092,
  384,
  13378],
 [806, 11, 53, 1788, 225, 318, 1058, 193, 1748, 973, 113],
 [4914,
  2100,
  454,
  11536,
  60,
  20,
  424,
  4,
  16123,
  3,
  1333,
  1,
  199,
  19,
  399,
  6,
  2983,
  692,
  6,
  203,
  173,
  308,
  321,
  247,
  7,
  32,
  55,
  161,
  2100,
  4,
  120,
  4914,
  2100,
  1102,
  169,
  5,
  473,
  8710],
 [94, 48, 15, 2110, 382, 200, 783, 681, 2103, 17053, 1106, 3, 14980, 1335],
 [44,
  2,
  31,
  533,
  27,
  353,
  65,
  2,
  290,
  49,
  11,
  2,
  31,
  108,
  2324,
  3,
  24,
  3,
  86,
  185,
  65,
  127,
  313,
  2709,
  60,
  4,
  2,
  63,
  3293,
  132,
  4,
  2,
  84,
  25,
  775,
  5,
  338,
  2266,
  5045,
  6059,
  136,
  34,
  38,
  27,
  2508,
  138,
  86],
 [2,
  31,
  213,
  421,
  49,
  65,
  230,
  2880,
  38,
  306,
  3,
  609,
  49,
  1,
  227,
  313,
  123,
  4,
  123,
  122,
  44,
  52,
  85,
  1963,
  17,
  61,
  858,
  313,
  9,
  120,
  1121,
  67,
  75,
  17,
  38,
  609,
  49,
  28,
  1,
  910,
  3521,
  13,
  74,
  66,
  67,
  13740,
  14730,
  30,
  61,
  1152],
 [97, 97, 257, 7, 105, 16027, 8035],
 [7,
  15,
  25,
  5,
  4461,
  7,

In [26]:
data["hashtags"].value_counts()

hashtags
[]    61692
Name: count, dtype: int64

In [27]:
data.columns

Index(['Text', 'Labels', 'clean_text', 'hashtags', 'mentions'], dtype='object')

In [28]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

#maxlen=200

max_len = max(len(x) for x in X_train_seq)

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len)

In [29]:
X_test_seq

[[1028,
  67,
  193,
  58,
  3619,
  4363,
  104,
  103,
  223,
  2373,
  129,
  7405,
  4,
  17504,
  172,
  156,
  21,
  507,
  9,
  2979,
  4,
  1629,
  9,
  346,
  16,
  15,
  507,
  2077,
  5795,
  2,
  31,
  835,
  163,
  230,
  77,
  34,
  11,
  17,
  198],
 [601,
  1786,
  2,
  118,
  16,
  310,
  2327,
  30,
  27,
  1817,
  10,
  9048,
  26,
  2,
  107,
  103,
  11,
  10,
  49,
  494,
  4,
  418,
  7,
  53,
  3,
  23,
  15645,
  317,
  45,
  116,
  1142,
  1,
  3226,
  8,
  1032,
  3842,
  4,
  274,
  27,
  1543,
  33,
  28,
  1084],
 [1922,
  32,
  5,
  90,
  432,
  53,
  1828,
  378,
  524,
  448,
  907,
  121,
  245,
  17020,
  2734,
  1292,
  53,
  4957,
  393,
  33],
 [9125, 2879, 1036, 6, 3338, 58, 5, 90, 1927, 1261, 1638, 1286, 1261],
 [2, 1495, 18165, 1132, 9, 9151],
 [332, 56],
 [1252,
  47,
  12,
  179,
  258,
  61,
  49,
  1,
  337,
  1321,
  50,
  15,
  1,
  447,
  6,
  254,
  5,
  83,
  1234,
  13,
  2792,
  59,
  61,
  129,
  511,
  6,
  14,
  77,
  5600,
  741,
  4,
  18010],
 [256,
  226,
  2,
  100,
  108,
  3,
  306,
  11,
  3,
  3419,
  4,
  86,
  50,
  18019,
  6,
  5700,
  3,
  949],
 [2,
  290,
  34,
  2,
  84,
  2810,
  1199,
  177,
  23035,
  9,
  170,
  335,
  1123,
  301,
  2101,
  1018,
  42,
  1,
  5175,
  330],
 [284, 156, 229, 2545, 176, 156, 95, 36, 39, 18, 16114],
 [23, 65, 1416, 64],
 [568, 59, 154, 9, 6, 203, 1381, 926, 231, 301, 678, 741, 4, 11253, 2942],
 [2347,
  4823,
  2181,
  15354,
  1050,
  1353,
  2692,
  76,
  5,
  4457,
  3,
  2059,
  6500,
  4,
  5290,
  13043,
  18,
  13044,
  819,
  407,
  2181,
  8,
  162],
 [2,
  24,
  3272,
  14,
  344,
  839,
  233,
  33,
  11,
  19,
  20,
  5,
  2132,
  6,
  1428,
  365,
  1044,
  34,
  267,
  3,
  42,
  55,
  6946,
  4,
  152,
  2,
  168,
  344,
  2,
  698,
  14,
  677,
  635,
  26,
  41,
  124,
  2,
  100,
  2031,
  2009,
  11,
  211,
  14,
  316,
  4605,
  437,
  177,
  175],
 [50,
  1,
  305,
  231,
  149,
  674,
  59,
  149,
  483,
  547,
  149,
  28,
  204,
  5,
  2826,
  10,
  8874,
  11,
  19],
 [423, 29, 3593, 16],
 [40, 3048, 5675, 8, 5, 1432, 220, 1432],
 [1647,
  177,
  224,
  3,
  225,
  2799,
  3,
  22,
  1246,
  851,
  7,
  269,
  17,
  87,
  24,
  3,
  22,
  13,
  1,
  53,
  19,
  2,
  164,
  7,
  126,
  22,
  5,
  90,
  489,
  10,
  71,
  104,
  822,
  17,
  9,
  247,
  16269,
  5,
  2285,
  6,
  1923,
  1828,
  2377,
  7,
  163],
 [230,
  6,
  12,
  30,
  53,
  216,
  1,
  172,
  263,
  212,
  15497,
  26,
  10,
  322,
  104,
  456,
  22,
  220,
  957,
  4850,
  695,
  34,
  23,
  19304,
  820,
  957,
  4850,
  8,
  9,
  1,
  315,
  1,
  153,
  8,
  270,
  26,
  301,
  5426,
  339,
  25,
  607,
  35,
  20,
  366,
  1902],
 [3566,
  2001,
  11,
  1116,
  155,
  28,
  143,
  335,
  2,
  31,
  3822,
  3,
  1432,
  1,
  265,
  60,
  113,
  1,
  265,
  155,
  28,
  737],
 [164,
  294,
  261,
  79,
  361,
  20,
  11,
  114,
  2000,
  377,
  128,
  16,
  460,
  72,
  706,
  49,
  1080,
  50,
  29,
  119,
  14,
  1560,
  720,
  34,
  2,
  31,
  19468,
  706,
  13,
  5,
  13093,
  6215,
  177,
  760],
 [75, 17, 22, 8869],
 [2, 243, 8482],
 [9162,
  14,
  540,
  8,
  9163,
  4,
  2,
  31,
  53,
  124,
  4,
  2,
  24,
  5,
  1515,
  973,
  1583,
  157,
  11578,
  134,
  6,
  1,
  71,
  66,
  337,
  3727,
  2690,
  233,
  4,
  85,
  3588,
  30,
  131,
  421,
  11579,
  164,
  9164,
  68,
  71,
  164,
  10,
  28,
  123,
  1,
  1648,
  534],
 [829, 113, 40, 351, 19, 53, 610, 1344, 27, 2932, 14, 1610],
 [2,
  100,
  2341,
  3,
  1136,
  16,
  2,
  32,
  388,
  6,
  1,
  2062,
  196,
  6,
  173,
  308,
  321,
  247,
  396,
  3797,
  10,
  193,
  104,
  839,
  20,
  23,
  13,
  7,
  4,
  6414,
  1,
  604,
  6206,
  249,
  18,
  171,
  137,
  9211,
  246],
 [16652, 48, 61, 374],
 [1858, 107, 2222, 45, 117],
 [21, 230, 226, 71, 9, 1, 2382, 15, 633],
 [791, 3, 522, 401, 14, 146, 115],
 [11, 70, 381, 733, 505, 6, 203, 1496, 1576, 350, 486, 1695],
 [30,
  38,
  108,
  3,
  819,
  5602,
  124,
  16,
  4,
  27,
  1312,
  16,
  43,
  30,
  315,
  12,
  139,
  620,
  424,
  38,
  30,
  647],
 [93, 330, 625, 5, 418, 5, 336, 772, 59, 1, 53, 501, 314, 32, 1768],
 [1855,
  425,
  389,
  1022,
  2,
  24,
  481,
  16,
  547,
  4060,
  58,
  72,
  667,
  471,
  3,
  7011,
  20029,
  1436,
  2,
  24,
  3,
  2408,
  16,
  68,
  6,
  1,
  3146,
  2,
  1122,
  20,
  4,
  874,
  30,
  25,
  351,
  36,
  39,
  18,
  14307,
  14308],
 [96, 82, 141, 1106, 3, 10568, 17, 198, 83, 246, 20086],
 [3290,
  52,
  194,
  115,
  804,
  66,
  88,
  522,
  401,
  1518,
  738,
  4589,
  662,
  1276,
  7,
  3,
  14,
  349,
  66,
  2790,
  44,
  449,
  44,
  149,
  97,
  368,
  35,
  52,
  149,
  89,
  20,
  23],
 [8,
  108,
  35,
  58,
  201,
  23,
  1561,
  65,
  70,
  100,
  20,
  1,
  259,
  8349,
  4,
  28,
  93,
  2183,
  113,
  313,
  1354,
  469,
  4,
  1,
  897,
  8,
  596,
  15180],
 [1448, 257, 60, 13, 1220, 210, 2458, 14, 344, 881, 37, 16, 883, 70, 19, 1476],
 [1010, 2150, 1943, 4, 2, 34, 7],
 [1, 134, 4824, 53, 94, 146, 115, 8, 5, 19, 12761, 601, 18, 4, 94, 15],
 [571,
  10,
  61,
  2312,
  227,
  19,
  4,
  61,
  1256,
  487,
  16372,
  4,
  73,
  554,
  2056,
  806,
  69,
  1,
  15095],
 [346,
  2,
  873,
  17,
  5,
  337,
  26,
  2,
  81,
  5,
  16783,
  2001,
  155,
  28,
  155,
  28,
  204,
  3,
  609,
  3,
  104,
  274,
  626,
  1469,
  911,
  145,
  156,
  12,
  1979,
  105,
  172,
  156,
  12,
  651,
  1486,
  8324,
  4664],
 [741, 402],
 [94, 146, 20, 1996, 207, 793, 850, 4, 23302, 752, 195, 94, 146, 115],
 [394, 47, 11, 97],
 [533,
  7,
  183,
  5118,
  4,
  5118,
  10,
  680,
  129,
  1,
  94,
  146,
  115,
  179,
  2,
  75,
  17,
  164,
  115,
  8,
  1,
  162,
  1465,
  10,
  23,
  26,
  41,
  2,
  31,
  61,
  6027],
 [946, 268, 686, 149, 15],
 [10660,
  144,
  12,
  10,
  3359,
  9,
  971,
  171,
  1,
  153,
  3,
  86,
  52,
  12,
  24,
  178,
  55,
  74,
  3632,
  455,
  764,
  145,
  130,
  10,
  194,
  372,
  3,
  238,
  45,
  41,
  10,
  218,
  1082,
  1082,
  2314,
  838,
  17,
  198,
  20925,
  20926],
 [307,
  4669,
  4330,
  60,
  1511,
  1200,
  96,
  1307,
  4764,
  154,
  35,
  3940,
  347,
  14020,
  946,
  268,
  4484,
  953,
  309],
 [11,
  8,
  93,
  507,
  2041,
  523,
  122,
  428,
  5,
  611,
  16,
  1512,
  3321,
  642,
  4,
  183,
  34,
  3710,
  2,
  688,
  290,
  135,
  10,
  102,
  152,
  2,
  43,
  45,
  2548,
  1839],
 [128,
  5,
  20616,
  2602,
  20,
  74,
  4,
  2,
  190,
  27,
  401,
  376,
  174,
  2,
  2034,
  5,
  1955,
  37,
  14,
  2399,
  3155,
  5811,
  23,
  10,
  1645,
  291,
  1446],
 [232, 171, 23, 14458, 14, 3917],
 [346, 12, 697],
 [154, 6, 203, 15, 1257, 8, 550, 129, 3903, 4275, 15, 4159, 421, 131, 421],
 [38, 30, 593, 3, 22, 334, 20, 22315, 13, 275, 4, 790, 5020, 33, 892],
 [21,
  214,
  1186,
  1727,
  8,
  286,
  152,
  92,
  7,
  58,
  5,
  295,
  6,
  408,
  4492,
  219,
  124,
  104,
  30,
  73,
  25,
  34,
  282,
  23,
  262,
  4,
  420,
  17,
  169,
  1,
  53,
  19,
  9,
  123,
  180,
  26,
  163,
  135,
  1,
  19,
  8,
  27,
  25,
  1629,
  550,
  129,
  1,
  714,
  4010,
  4792],
 [2, 281, 254, 682, 459, 20, 151, 236, 13, 1, 2327, 4, 7, 15, 27, 1, 379],
 [205, 2262, 3, 40, 541, 13, 88, 7, 15, 28, 25, 91, 769, 109, 11],
 [767, 3, 212, 10, 6069, 5, 1282, 14463, 314, 9, 110, 2073, 4200],
 [127,
  2764,
  281,
  283,
  17609,
  1651,
  33,
  40,
  6051,
  17610,
  101,
  150,
  95,
  95,
  95,
  95,
  36,
  39,
  18,
  17611,
  83],
 [1,
  1428,
  212,
  1044,
  15971,
  518,
  410,
  4423,
  13725,
  7007,
  3559,
  237,
  1330,
  142,
  112,
  15972],
 [2, 25, 1562, 9401, 15, 1341, 1008],
 [5414, 1998, 5414],
 [11880,
  1586,
  1586,
  6145,
  807,
  3429,
  4,
  4083,
  294,
  504,
  38,
  826,
  17,
  812,
  12,
  904,
  147,
  2013],
 [81,
  1251,
  123,
  9,
  5,
  1403,
  1008,
  92,
  2,
  81,
  1681,
  2056,
  2,
  1299,
  2950,
  1431,
  445,
  43,
  139,
  25,
  5,
  646,
  6030,
  288,
  109,
  28,
  4,
  859,
  16,
  407,
  12,
  99,
  244,
  66,
  87,
  636,
  6,
  487,
  30,
  3,
  22,
  1787,
  4,
  85,
  8,
  56,
  224,
  10,
  102,
  29,
  285,
  219],
 [50, 1, 89],
 [7436,
  2098,
  3997,
  849,
  50,
  637,
  69,
  8099,
  1328,
  13,
  11,
  66,
  107,
  328,
  1117,
  76,
  18,
  759,
  20248,
  20249,
  20250,
  159,
  17,
  20251,
  317],
 [54, 16231, 1522, 20, 604],
 [114, 2540, 1003, 7024, 268, 284, 83, 345],
 [212, 316, 2425, 890, 24, 125, 1184, 3, 198],
 [1, 1003],
 [3,
  801,
  61,
  6,
  14,
  605,
  278,
  79,
  196,
  170,
  6,
  669,
  160,
  20,
  976,
  1677,
  16,
  139,
  15,
  1,
  447],
 [136, 264, 35, 11, 161, 761],
 [297,
  117,
  3884,
  18383,
  15631,
  18,
  882,
  117,
  19989,
  1236,
  423,
  17,
  198,
  21031,
  21032],
 [10162,
  4234,
  10,
  19643,
  5,
  336,
  260,
  6,
  132,
  2,
  81,
  614,
  9,
  631,
  10,
  168,
  477,
  21,
  2,
  29,
  17,
  119,
  60,
  62,
  504,
  14,
  2140,
  142,
  112,
  17146],
 [33,
  1,
  227,
  62,
  598,
  1,
  404,
  16,
  85,
  30,
  458,
  68,
  464,
  71,
  669,
  608,
  1,
  879,
  440,
  134,
  6,
  102,
  47,
  27,
  24,
  280,
  3,
  273,
  454,
  4,
  47,
  27,
  24,
  280,
  3,
  273,
  258,
  211,
  134,
  6,
  102,
  47,
  27,
  24,
  280,
  3,
  273,
  258],
 [26, 2, 29, 17, 6107],
 [301,
  176,
  20,
  11,
  2760,
  6,
  14,
  304,
  450,
  11,
  348,
  4,
  14,
  799,
  304,
  450,
  6,
  569,
  104,
  8,
  40,
  304,
  450,
  6,
  569],
 [6448, 4886, 1506, 21040, 30, 334, 13, 55, 1716, 349, 4, 3391, 615, 15, 3161],
 [],
 [303],
 [14, 1687, 8, 16324, 4, 14, 130, 8, 1491],
 [1, 528, 516, 1539, 12469, 17071, 1180, 1065, 12470, 8227],
 [257, 1, 763, 226, 5533, 163],
 [220, 16373, 8, 27, 1588],
 [63, 302],
 [145, 62, 2, 342, 4, 243, 463, 10, 7, 128, 8, 48, 6, 339, 244],
 [65, 190, 346, 45, 5, 550, 19, 129, 319, 83],
 [2,
  118,
  16,
  14067,
  1057,
  32,
  1256,
  9,
  11026,
  21,
  270,
  470,
  445,
  7,
  460,
  34,
  5,
  1544,
  3,
  24,
  105,
  25,
  147,
  1143,
  177,
  1686,
  10,
  5,
  591,
  5322,
  6,
  11026,
  387,
  208,
  87,
  225,
  1,
  1420,
  416,
  10,
  7,
  44,
  55,
  527],
 [199, 597, 1067, 204, 3, 24, 68, 90, 93, 77, 189],
 [1716, 969, 208, 41, 384, 61, 129, 242, 622, 736],
 [7],
 [25,
  50,
  403,
  2,
  350,
  10,
  202,
  942,
  235,
  436,
  2058,
  548,
  4,
  41,
  68,
  419,
  3,
  281,
  105,
  272,
  28,
  3036],
 [35,
  6,
  28,
  1,
  349,
  3441,
  3,
  24,
  15987,
  4643,
  116,
  8,
  1,
  107,
  3,
  27,
  24,
  7,
  4,
  2,
  1701,
  24,
  55,
  580,
  20,
  14,
  349],
 [2,
  75,
  17,
  575,
  67,
  11,
  19,
  58,
  576,
  21,
  270,
  216,
  1,
  32,
  655,
  6,
  5,
  23828,
  1461],
 [30, 94, 265, 182, 66, 24, 2, 72, 1318],
 [3049, 2992],
 [829,
  453,
  703,
  1761,
  2,
  100,
  210,
  81,
  1825,
  167,
  3,
  14,
  121,
  116,
  962,
  2,
  31,
  136,
  21,
  221,
  3,
  171,
  1,
  8085,
  4,
  25,
  940,
  701,
  22437,
  70],
 [4007,
  3963,
  13711,
  5637,
  7372,
  7373,
  6828,
  4347,
  4007,
  74,
  18,
  1425,
  345,
  427,
  13712,
  215,
  74],
 [2,
  84,
  1856,
  983,
  8467,
  1158,
  101,
  150,
  4,
  28,
  10829,
  754,
  398,
  1452,
  16,
  281,
  105,
  28,
  827],
 [7, 15, 21, 326, 59, 11, 854],
 [78, 497, 9, 1, 19, 394, 1151, 23],
 [27, 5, 51, 4305, 10, 677, 20],
 [209,
  238,
  5,
  114,
  1254,
  492,
  53,
  153,
  188,
  22,
  9189,
  9190,
  84,
  1824,
  3506,
  13,
  153,
  7752,
  7491],
 [104, 2210, 197, 23, 11, 70, 294, 1760, 3, 596, 376],
 [585],
 [48, 69, 1, 78, 4556, 219, 69, 4],
 [282,
  1707,
  54,
  6648,
  34,
  23,
  4,
  350,
  34,
  431,
  32,
  108,
  3,
  1589,
  291,
  116,
  354,
  92,
  1088,
  2,
  753,
  291,
  50,
  38,
  394,
  168,
  13,
  20006,
  3921,
  4,
  12,
  364,
  113,
  3,
  7,
  34,
  467,
  64],
 [346,
  257,
  105,
  1,
  3268,
  4724,
  373,
  1798,
  217,
  8,
  279,
  226,
  3,
  86,
  33,
  11,
  156,
  15,
  301,
  2608],
 [264, 35, 1, 761, 2, 25, 81, 1282, 15499, 12096],
 [64,
  64,
  26,
  67,
  12,
  197,
  531,
  3285,
  11,
  6619,
  114,
  22,
  1,
  297,
  4,
  65,
  4,
  152,
  16,
  15,
  56,
  51,
  56,
  53,
  77,
  285,
  6619,
  209,
  50,
  795,
  701,
  1952,
  3979,
  56,
  504,
  154,
  6,
  203,
  693,
  731,
  5701,
  56,
  504,
  40,
  488],
 [2, 416, 3, 47, 11, 111, 1091, 1497, 4599, 30, 14739],
 [38,
  139,
  99,
  477,
  37,
  100,
  79,
  4985,
  1818,
  1178,
  1,
  537,
  170,
  38,
  84,
  483,
  1,
  255,
  6,
  6263,
  24,
  5,
  90,
  2812,
  771,
  4,
  51,
  555,
  9],
 [43,
  24,
  213,
  2858,
  51,
  219,
  10,
  1214,
  56,
  930,
  2566,
  7,
  8,
  9,
  234,
  367,
  91,
  26,
  43,
  84,
  213,
  1191,
  43,
  139,
  25,
  5270,
  3,
  6259,
  385,
  15,
  6222,
  15969,
  874,
  168,
  92,
  12,
  420,
  17,
  5222,
  376,
  1261,
  2090,
  13722,
  353],
 [97,
  683,
  11,
  6610,
  3374,
  15,
  101,
  457,
  97,
  4,
  144,
  12,
  7,
  490,
  27,
  254,
  1,
  15,
  101,
  59,
  27,
  254,
  1,
  11811],
 [2, 63, 170, 6, 160, 142, 112, 14772],
 [13,
  297,
  165,
  16,
  12,
  1589,
  1,
  401,
  26,
  12,
  1174,
  16,
  630,
  58,
  1712,
  1,
  401,
  3727,
  12,
  140,
  3,
  14703],
 [303],
 [117, 661, 8, 1, 326, 626, 117, 6, 28, 62],
 [2, 504, 26, 67, 762, 21, 121, 307, 33, 81, 23, 667],
 [8369,
  8,
  69,
  375,
  1,
  326,
  379,
  2,
  84,
  138,
  103,
  193,
  841,
  3,
  324,
  5,
  392,
  20,
  23,
  4,
  38,
  29,
  306,
  1,
  227,
  4586,
  44,
  116,
  4,
  1485,
  4,
  33,
  17,
  38,
  29,
  193,
  20,
  3085,
  3131,
  4154,
  143,
  14,
  2741,
  58,
  7],
 [563, 2, 206, 878],
 [570,
  2298,
  298,
  2298,
  25,
  41,
  169,
  1,
  121,
  1534,
  10,
  11,
  348,
  292,
  887,
  12,
  190,
  5,
  90,
  168,
  13,
  1,
  347,
  4,
  1,
  8556,
  364,
  143,
  10,
  1,
  199,
  48,
  49,
  168],
 [534,
  600,
  23,
  35,
  80,
  8,
  108,
  3,
  1657,
  5,
  2929,
  35,
  6,
  111,
  259,
  3,
  54,
  2368,
  67,
  12,
  202,
  2715,
  55,
  94,
  146,
  115,
  1715,
  5,
  88],
 [5, 3868, 20921, 3, 119, 5, 15480, 1245, 132, 142, 112, 15481],
 [425,
  67,
  58,
  1,
  501,
  6,
  1,
  94,
  48,
  115,
  72,
  3652,
  15399,
  216,
  1,
  172,
  225,
  131,
  1402,
  1804],
 [2,
  24,
  4762,
  1025,
  10,
  5578,
  763,
  104,
  1239,
  33,
  1,
  3244,
  3468,
  101,
  150,
  1232,
  15,
  9,
  1,
  321,
  2543,
  28,
  3442,
  25,
  3,
  42,
  12040],
 [114,
  18,
  732,
  105,
  9545,
  408,
  7256,
  670,
  4937,
  9546,
  3428,
  20,
  20709,
  4,
  218,
  15562,
  10,
  8357,
  3685,
  9548,
  18,
  2812,
  114],
 [101,
  150,
  3446,
  1725,
  10764,
  16,
  1680,
  5590,
  123,
  4538,
  4,
  24,
  5459,
  2406,
  330,
  453,
  2264,
  34,
  10765],
 [3975, 20, 2039, 96, 9, 4140, 13499, 18, 3537],
 [16,
  15,
  162,
  26,
  11,
  70,
  2944,
  14,
  645,
  2,
  84,
  72,
  79,
  1850,
  216,
  110,
  371,
  4,
  446,
  2973,
  216,
  1,
  121,
  19,
  2,
  31,
  421,
  3,
  86,
  7,
  1003,
  2215,
  33,
  5,
  492,
  569],
 [11,
  491,
  55,
  408,
  3107,
  1465,
  75,
  17,
  42,
  23,
  433,
  104,
  63,
  12505,
  12506,
  3107,
  10,
  7,
  460,
  5,
  336,
  165,
  2,
  31,
  2017,
  2,
  42,
  3229,
  433,
  445],
 [2,
  416,
  5,
  1019,
  12761,
  4,
  15140,
  3,
  22,
  5,
  844,
  9,
  5,
  245,
  512,
  145,
  312,
  4,
  41,
  14,
  1884,
  30,
  4954,
  1557],
 [40,
  872,
  8,
  5,
  93,
  868,
  1611,
  6852,
  16464,
  7,
  15,
  34,
  1696,
  6,
  12,
  93,
  4968,
  187,
  169,
  1134,
  332,
  29,
  17,
  143,
  1087,
  83,
  4391,
  12,
  93,
  2281,
  35,
  6,
  392,
  47,
  228,
  2060,
  10,
  5,
  434,
  4,
  612,
  99,
  18461,
  93,
  952],
 [78,
  388,
  8,
  133,
  6639,
  250,
  15,
  4206,
  367,
  91,
  10,
  3324,
  188,
  22,
  246,
  11427,
  330,
  17],
 [59, 12, 368, 35, 12, 84, 1814, 785, 1, 94, 48, 115, 505, 6, 1, 94, 146, 115],
 [7, 15, 412],
 [530,
  11,
  8,
  162,
  60,
  14,
  16597,
  2,
  1260,
  1241,
  152,
  1111,
  7,
  165,
  2,
  29,
  17,
  324,
  3,
  18918,
  11,
  20,
  14,
  9103,
  9,
  1,
  847],
 [246, 83, 919, 684],
 [74,
  6910,
  60,
  53,
  2544,
  465,
  937,
  3468,
  1529,
  109,
  3202,
  428,
  2501,
  792,
  3044,
  18,
  664,
  3018],
 [5678,
  16,
  218,
  98,
  14484,
  32,
  5,
  507,
  489,
  123,
  18957,
  3,
  24,
  5,
  4431,
  768,
  1244,
  478,
  4,
  2017,
  10097,
  742,
  5678,
  50,
  7,
  223,
  3,
  91,
  45,
  1,
  3681,
  16721,
  33,
  409,
  2592],
 [672,
  6,
  2249,
  6577,
  292,
  38,
  538,
  1,
  71,
  104,
  614,
  12,
  35,
  13,
  40,
  696,
  59,
  12,
  231,
  163,
  93,
  2249,
  3,
  465,
  858,
  9234,
  4,
  3,
  1859,
  3,
  4,
  1205,
  9235,
  10,
  55,
  858,
  1545,
  26,
  12,
  103,
  1,
  62,
  3,
  465,
  49,
  93,
  117,
  4999,
  44,
  52,
  12],
 [14,
  498,
  33,
  7375,
  4933,
  906,
  32,
  1096,
  397,
  15293,
  13,
  98,
  215,
  1949,
  1949,
  18,
  7375,
  4933],
 [468,
  1120,
  6,
  913,
  569,
  574,
  10,
  315,
  5,
  51,
  1438,
  472,
  275,
  5,
  18,
  5,
  284,
  9925],
 [11, 220, 5177, 9, 96, 808, 263, 6, 691, 242, 13, 23],
 [2, 229, 2422, 184, 578],
 [473,
  144,
  12,
  3,
  193,
  104,
  515,
  60,
  69,
  105,
  128,
  504,
  38,
  103,
  3,
  373,
  1,
  451,
  79,
  13,
  5,
  277,
  152,
  7396,
  4,
  17,
  17,
  1192,
  27,
  3995,
  14,
  711,
  87,
  61,
  1,
  451,
  38,
  2508,
  1080,
  908,
  477,
  482,
  87,
  119,
  7,
  28,
  1,
  224,
  305,
  703,
  257,
  33,
  23,
  68,
  61,
  88,
  3243,
  146,
  32,
  301,
  51,
  136],
 [21, 2, 422, 1670, 96, 3476, 4, 781, 71, 10, 56, 429, 441, 23],
 [1,
  698,
  436,
  1259,
  1,
  8607,
  64,
  7457,
  8,
  35,
  41,
  69,
  74,
  734,
  4610,
  1072,
  4,
  161,
  1072,
  50,
  482,
  942,
  59,
  4139,
  210,
  1294,
  847,
  11267,
  65,
  850,
  8,
  15770,
  1,
  8607,
  1106,
  3,
  15771],
 [303],
 [7,
  206,
  15,
  136,
  1402,
  65,
  174,
  184,
  269,
  17,
  87,
  47,
  352,
  177,
  2973,
  4031,
  1207,
  9,
  727,
  19,
  34,
  55,
  3027,
  399,
  250,
  12,
  875,
  242,
  716,
  695,
  10,
  498,
  564,
  4,
  196,
  947,
  4,
  30,
  213,
  13],
 [28,
  162,
  17276,
  8,
  1604,
  1545,
  8,
  73,
  5,
  3923,
  6,
  3955,
  10286,
  8,
  795,
  1,
  19,
  8,
  3608,
  8196,
  1,
  19,
  183,
  161,
  43,
  84,
  210,
  980,
  1,
  2594,
  1227,
  531,
  198,
  20582,
  20583],
 [292, 2, 31, 1151, 221],
 [1669, 9, 3724],
 [41,
  16,
  2,
  84,
  2111,
  910,
  4269,
  6,
  5,
  3765,
  1040,
  2,
  519,
  7,
  61,
  129,
  138,
  87,
  445,
  2,
  107,
  201,
  7,
  3,
  1490,
  6,
  96,
  82,
  141],
 [136,
  924,
  52,
  14,
  189,
  29,
  17,
  197,
  235,
  385,
  88,
  1348,
  6,
  16,
  784,
  488,
  457],
 [7],
 [1046,
  130,
  6,
  12,
  1048,
  5,
  3756,
  37,
  23,
  33,
  11,
  447,
  2,
  258,
  61,
  49,
  12,
  835,
  5,
  3338,
  129,
  1,
  62,
  4,
  233,
  1,
  3756,
  58,
  72,
  455,
  1972],
 [79, 7821, 112, 6720, 42, 20864],
 [48,
  6,
  14,
  380,
  13,
  1,
  88,
  8,
  5,
  10999,
  235,
  76,
  465,
  11,
  478,
  397,
  283,
  9,
  5,
  15092,
  384,
  13378],
 [806, 11, 53, 1788, 225, 318, 1058, 193, 1748, 973, 113],
 [4914,
  2100,
  454,
  11536,
  60,
  20,
  424,
  4,
  16123,
  3,
  1333,
  1,
  199,
  19,
  399,
  6,
  2983,
  692,
  6,
  203,
  173,
  308,
  321,
  247,
  7,
  32,
  55,
  161,
  2100,
  4,
  120,
  4914,
  2100,
  1102,
  169,
  5,
  473,
  8710],
 [94, 48, 15, 2110, 382, 200, 783, 681, 2103, 17053, 1106, 3, 14980, 1335],
 [44,
  2,
  31,
  533,
  27,
  353,
  65,
  2,
  290,
  49,
  11,
  2,
  31,
  108,
  2324,
  3,
  24,
  3,
  86,
  185,
  65,
  127,
  313,
  2709,
  60,
  4,
  2,
  63,
  3293,
  132,
  4,
  2,
  84,
  25,
  775,
  5,
  338,
  2266,
  5045,
  6059,
  136,
  34,
  38,
  27,
  2508,
  138,
  86],
 [2,
  31,
  213,
  421,
  49,
  65,
  230,
  2880,
  38,
  306,
  3,
  609,
  49,
  1,
  227,
  313,
  123,
  4,
  123,
  122,
  44,
  52,
  85,
  1963,
  17,
  61,
  858,
  313,
  9,
  120,
  1121,
  67,
  75,
  17,
  38,
  609,
  49,
  28,
  1,
  910,
  3521,
  13,
  74,
  66,
  67,
  13740,
  14730,
  30,
  61,
  1152],
 [97, 97, 257, 7, 105, 16027, 8035],
 [7,
  15,
  25,
  5,
  4461,
  7,

In [30]:
df_train = pd.DataFrame(X_train_seq)
df_train.to_csv("X_train_data.csv", index=False)

df_test = pd.DataFrame(X_test_seq)
df_test.to_csv("X_test_data.csv", index=False)

df_test = pd.DataFrame(y_test)
df_test.to_csv("y_test_data.csv", index=False)
df_test = pd.DataFrame(y_train)
df_test.to_csv("y_train_data.csv", index=False)

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *